preliminary storage on F2FS support

diff --git a/scripts/mkimage b/scripts/mkimage
--- a/scripts/mkimage
+++ b/scripts/mkimage
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/bin/bash -x
 
 # SPDX-License-Identifier: GPL-2.0-or-later
 # Copyright (C) 2009-2016 Stephan Raue (stephan@openelec.tv)
@@ -6,6 +6,7 @@
 # Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)
 # Copyright (C) 2022-present Fewtarius
 # Copyright (C) 2022-present UnofficialOS
+# Copyright (C) 2022-present NeoTheFox (http://github.com/NeoTheFox)
 
 ################################################################################
 # variables such as ${ROOT} ${PATH} etc... that are required for this
@@ -22,7 +23,7 @@ if [ -z "${SYSTEM_SIZE}" -o -z "${SYSTEM_PART_START}" ]; then
   exit 1
 fi
 
-STORAGE_SIZE=32 # STORAGE_SIZE must be >= 32 !
+STORAGE_SIZE=64 # STORAGE_SIZE must be >= 32 !
 
 DISK_START_PADDING=$(( (${SYSTEM_PART_START} + 2048 - 1) / 2048 ))
 DISK_GPT_PADDING=1
@@ -52,11 +53,27 @@ show_error() {
   exit 1
 }
 
+# using UUID for MBR and PARTUUID for gpt
+format_uuid() {
+  if [ "${PARTITION_TABLE}" = "mbr" ]; then
+    echo "UUID=${1}"
+  else
+    echo "PARTUUID=${1}"
+  fi
+  exit 1
+}
+
 trap cleanup SIGINT
 
 # create an image
 echo -e "\nimage: creating file $(basename ${DISK})..."
 dd if=/dev/zero of="${DISK}" bs=1M count="${DISK_SIZE}" conv=fsync >"${SAVE_ERROR}" 2>&1 || show_error
+
+if [ "${STORAGE_FS}" = "f2fs" ] && [ "${PARTITION_TABLE}" == "mbr" ]
+then
+    echo "Can't use F2FS with MBR! Falling back to ext4..."
+    STORAGE_FS="ext4"
+fi
 
 echo "image: creating partition table (${PARTITION_TABLE})..."
 parted -s "${DISK}" mklabel ${PARTITION_TABLE}
@@ -75,6 +92,7 @@ SYSTEM_PART_END=$(( ${SYSTEM_PART_START} + (${SYSTEM_SIZE} * 1024 * 1024 / 512) 
 if [ "${PARTITION_TABLE}" = "gpt" ]; then
   echo "image: Create boot partition."
   parted -s "${DISK}" -a min unit s mkpart boot fat32 ${SYSTEM_PART_START} ${SYSTEM_PART_END}
+  sgdisk --partition-guid=1:${UUID_SYSTEM}
 else
   echo "image: Create primary partition."
   parted -s "${DISK}" -a min unit s mkpart primary fat32 ${SYSTEM_PART_START} ${SYSTEM_PART_END}
@@ -88,10 +106,11 @@ STORAGE_PART_START=$(( ${SYSTEM_PART_END} + 1 ))
 STORAGE_PART_END=$(( ${STORAGE_PART_START} + (${STORAGE_SIZE} * 1024 * 1024 / 512) - 1 ))
 if [ "${PARTITION_TABLE}" = "gpt" ]; then
     echo "image: Create storage partition."
-    parted -s "${DISK}" -a min unit s mkpart storage ext4 ${STORAGE_PART_START} ${STORAGE_PART_END}
+    parted -s "${DISK}" -a min unit s mkpart storage ${STORAGE_FS} ${STORAGE_PART_START} ${STORAGE_PART_END}
+    sgdisk --partition-guid=2:${UUID_STORAGE}
   else
     echo "image: Create primary partition."
-    parted -s "${DISK}" -a min unit s mkpart primary ext4 ${STORAGE_PART_START} ${STORAGE_PART_END}
+    parted -s "${DISK}" -a min unit s mkpart primary ${STORAGE_FS} ${STORAGE_PART_START} ${STORAGE_PART_END}
 fi
 sync
 
@@ -130,7 +149,7 @@ NOESCAPE 1
 
 LABEL run
   KERNEL /${KERNEL_NAME}
-  APPEND boot=UUID=${UUID_SYSTEM} disk=UUID=${UUID_STORAGE} portable ${EXTRA_CMDLINE}
+  APPEND boot=$(format_uuid ${UUID_SYSTEM}) disk=$(format_uuid ${UUID_STORAGE}) portable ${EXTRA_CMDLINE}
 EOF
 
   cat << EOF > "${LE_TMP}/grub.cfg"
@@ -138,7 +157,7 @@ set timeout="0"
 set default="Run"
 menuentry "Run" {
 	search --set -f /KERNEL
-	linux /KERNEL boot=UUID=${UUID_SYSTEM} disk=UUID=${UUID_STORAGE} grub_portable ${EXTRA_CMDLINE}
+    linux /KERNEL boot=$(format_uuid${UUID_SYSTEM}) disk=$(format_uuid${UUID_STORAGE}) grub_portable ${EXTRA_CMDLINE}
 }
 EOF
 
@@ -165,7 +184,7 @@ elif [ "${BOOTLOADER}" = "bcm2835-bootloader" ]; then
   # create bootloader configuration
   echo "image: creating bootloader configuration..."
   cat << EOF > "${LE_TMP}/cmdline.txt"
-boot=UUID=${UUID_SYSTEM} disk=UUID=${UUID_STORAGE} quiet ${EXTRA_CMDLINE}
+boot=$(format_uuid ${UUID_SYSTEM}) disk=$(format_uuid ${UUID_STORAGE}) quiet ${EXTRA_CMDLINE}
 EOF
 
   mcopy "${LE_TMP}/cmdline.txt" ::
@@ -234,26 +253,36 @@ fi # bootloader
 echo "image: extracting part2 from image..."
 STORAGE_PART_COUNT=$(( ${STORAGE_PART_END} - ${STORAGE_PART_START} + 1 ))
 sync
-dd if="${DISK}" of="${LE_TMP}/part2.ext4" bs=512 skip="${STORAGE_PART_START}" count="${STORAGE_PART_COUNT}" conv=fsync >"${SAVE_ERROR}" 2>&1 || show_error
+dd if="${DISK}" of="${LE_TMP}/part2.${STORAGE_FS}" bs=512 skip="${STORAGE_PART_START}" count="${STORAGE_PART_COUNT}" conv=fsync >"${SAVE_ERROR}" 2>&1 || show_error
 
 # create filesystem on part2
 echo "image: creating filesystem on part2..."
-mke2fs -F -q -t ext4 -m 0 "${LE_TMP}/part2.ext4"
-tune2fs -L "${DISTRO_DISKLABEL}" -U ${UUID_STORAGE} "${LE_TMP}/part2.ext4" >"${SAVE_ERROR}" 2>&1 || show_error
-e2fsck -n "${LE_TMP}/part2.ext4" >"${SAVE_ERROR}" 2>&1 || show_error
+if [ "${STORAGE_FS}" = "ext4" ]; then
+  mke2fs -F -q -t ${STORAGE_FS} -m 0 "${LE_TMP}/part2.${STORAGE_FS}"
+  tune2fs -L "${DISTRO_DISKLABEL}" -U ${UUID_STORAGE} "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
+  e2fsck -n "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
+elif [ "${STORAGE_FS}" = "f2fs" ]; then
+  mkfs.f2fs -q -O extra_attr,compression -l "${DISTRO_DISKLABEL}" "${LE_TMP}/part2.${STORAGE_FS}"
+  fsck.f2fs -a -f "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
+fi
 sync
 
 # add resize mark
 mkdir "${LE_TMP}/part2.fs"
 touch "${LE_TMP}/part2.fs/.please_resize_me"
 echo "image: populating filesystem on part2..."
-populatefs -U -d "${LE_TMP}/part2.fs" "${LE_TMP}/part2.ext4" >"${SAVE_ERROR}" 2>&1 || show_error
+populatefs -U -d "${LE_TMP}/part2.fs" "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
 sync
-e2fsck -n "${LE_TMP}/part2.ext4" >"${SAVE_ERROR}" 2>&1 || show_error
+if [ "${STORAGE_FS}" = "ext4" ]; then
+    e2fsck -n "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
+elif [ "${STORAGE_FS}" = "f2fs" ]; then
+    fsck.f2fs -a -f "${LE_TMP}/part2.${STORAGE_FS}" >"${SAVE_ERROR}" 2>&1 || show_error
+fi
+sync
 
 # merge part2 back to disk image
 echo "image: merging part2 back to image..."
-dd if="${LE_TMP}/part2.ext4" of="${DISK}" bs=512 seek="${STORAGE_PART_START}" conv=fsync,notrunc >"${SAVE_ERROR}" 2>&1 || show_error
+dd if="${LE_TMP}/part2.${STORAGE_FS}" of="${DISK}" bs=512 seek="${STORAGE_PART_START}" conv=fsync,notrunc >"${SAVE_ERROR}" 2>&1 || show_error
 
 # extract part1 from image to run fsck
 echo "image: extracting part1 from image..."
